# ansible/inventory/hosts.yml
# ansible all -i ansible/inventory/hosts.yml -m ping --ask-vault-pass
---
all:
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    master:
      hosts:
        pi-master:
          ansible_user: "{{ vault_ansible_user }}"
          ansible_host: 10.0.0.154
          node_ip: 10.0.0.154
          ansible_password: "{{ vault_master_password }}"
          ansible_become_password: "{{ vault_master_become_password }}"
          
    workers:
      hosts:
        pi-worker1:
          ansible_user: "{{ vault_ansible_user }}"
          ansible_host: 10.0.0.46
          node_ip: 10.0.0.46
          ansible_password: "{{ vault_worker1_password }}"
          ansible_become_password: "{{ vault_worker1_password }}"
        pi-worker2:
          ansible_user: "{{ vault_ansible_user }}"
          ansible_host: 10.0.0.189
          node_ip: 10.0.0.189
          ansible_password: "{{ vault_worker2_password }}"
          ansible_become_password: "{{ vault_worker2_password }}"
          
    k3s_cluster:
      children:
        master:
        workers: