$ANSIBLE_VAULT;1.1;AES256
37656439373838663735373930356532656434333635353261396463666162353831393733663162
3437333132613732343638666131636266643038333263650a373137393637353631396434386330
31326361356261336262643334656130636639383762666133646464386265313864633639333134
3562386637653063360a666166393733353366316266306161613764303062663465393235393265
31643932643130646638666130626631653331346138346534353630383236663033663939376332
35336166636538333966343064313937313765346133623735343332623536313434323939643763
62396135373362653830353331613661303532373738616663646463363366633131333739613662
63393836666565623334646166626666633130323534303738343961323866626462613637333637
36626437636531373438393439303061646433306439653261343364656132633536653932333839
35633563623932396535333666623661343833613731343237626162323636303230353331373735
39663431393265643563623637613133383433666336333762656131663138626364613730333133
31343763623436613364623436396162626236396139623034656164393664653633323565646337
62336664353436343537613032306663396362633936326561386264633131313037
